language: csharp
solution: WF_lab3.sln
install:
- nuget restore ./WF_lab3/WF_lab3.sln
- nuget install NUnit.Runners -Version 3.7.0 -OutputDirectory testrunner
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
- xbuild /p:Configuration=Release WF_lab3/WF_lab3.sln
- mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./WF_lab3/test/bin/Release/test.dll